# Generated by Django 5.1.2 on 2024-12-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_member_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FAQS',
        ),
    ]
